# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 1000

[custom.vim_insert_mode]
command = '''
if [[ ${ZSH_VIM_MODE} != vicmd ]]; then
  echo "[I]"
fi
'''
when = true
shell = ["zsh"]
style = "bold green"

[custom.vim_normal_mode]
command = '''
if [[ ${ZSH_VIM_MODE} == vicmd ]]; then
  echo "[N]"
fi
'''
when = true
shell = ["zsh"]
style = "bold blue"

[aws]
disabled = true

[directory]
truncation_symbol = '../'
truncate_to_repo = false

[directory.substitutions]
'~/Workspace' = '~/w'
'~/Developer' = '~/dev'

[git_branch]
symbol = " "

[git_status]
stashed = ''

[username]
# show_always = true
format = 'brady: ($style)'
