# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 1000

[aws]
disabled = true

# Optional: disable the dangling character in Warp
[character]
disabled = false

[directory]
truncation_symbol = '../'
truncate_to_repo = false

[directory.substitutions]
'~/Workspace' = '~/w'

[docker_context]
disabled = true

[git_branch]
symbol = " "

[package]
# display_private = true

[username]
# show_always = true
format = 'brady: ($style)'
